INSERT INTO Topic (TopicName) VALUES ("Web Development");
INSERT INTO Topic (TopicName) VALUES ("Machine Learning");
INSERT INTO Topic (TopicName) VALUES ("Android"); 
INSERT INTO Topic (TopicName) VALUES ("Gaming"); 
INSERT INTO Topic (TopicName) VALUES ("APIs");
INSERT INTO Topic (TopicName) VALUES ("iOS");
INSERT INTO Topic (TopicName) VALUES ("Operating Systems");
INSERT INTO Topic (TopicName) VALUES ("Artificial Intelligence"); 
INSERT INTO Topic (TopicName) VALUES ("Robotics");
INSERT INTO Topic (TopicName) VALUES ("Security");
INSERT INTO Topic (TopicName) VALUES ("Testing");
INSERT INTO Topic (TopicName) VALUES ("Web Frameworks");
INSERT INTO Topic (TopicName) VALUES ("Databases"); 
INSERT INTO Topic (TopicName) VALUES ("DevOps"); 
INSERT INTO Topic (TopicName) VALUES ("Augmented Reality");
INSERT INTO Topic (TopicName) VALUES ("Cryptocurrency");
INSERT INTO Topic (TopicName) VALUES ("Data Visualization");
INSERT INTO Topic (TopicName) VALUES ("Documentation"); 